services:
  - docker
env:
  global:
    - SHA=$(get rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
   - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project seismic-sweep-263614
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials multi-cluster
  - chmod +x mvnw
  - docker pull openjdk:8-jdk-alpine
script:
  - mvn test
  - mvn clean package
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master